// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPpVff0XlPhIaX8TEPGetl32zamat7WiQ',
    appId: '1:525600832054:web:a39b03d8d79ffd15cab697',
    messagingSenderId: '525600832054',
    projectId: 'chikitsya-a1e2d',
    authDomain: 'chikitsya-a1e2d.firebaseapp.com',
    storageBucket: 'chikitsya-a1e2d.firebasestorage.app',
    measurementId: 'G-YM8WDVJ7L8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdwwRtaEgvNKcaYosD_aswcUO29sUXkC8',
    appId: '1:525600832054:android:07c0071eae8acb5fcab697',
    messagingSenderId: '525600832054',
    projectId: 'chikitsya-a1e2d',
    storageBucket: 'chikitsya-a1e2d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmWVV9hnp2pGz5-c12z-9urWl7c5aHPak',
    appId: '1:525600832054:ios:80738e5c230ecce0cab697',
    messagingSenderId: '525600832054',
    projectId: 'chikitsya-a1e2d',
    storageBucket: 'chikitsya-a1e2d.firebasestorage.app',
    iosBundleId: 'com.example.chikitsya',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmWVV9hnp2pGz5-c12z-9urWl7c5aHPak',
    appId: '1:525600832054:ios:80738e5c230ecce0cab697',
    messagingSenderId: '525600832054',
    projectId: 'chikitsya-a1e2d',
    storageBucket: 'chikitsya-a1e2d.firebasestorage.app',
    iosBundleId: 'com.example.chikitsya',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPpVff0XlPhIaX8TEPGetl32zamat7WiQ',
    appId: '1:525600832054:web:80b974927a363c9dcab697',
    messagingSenderId: '525600832054',
    projectId: 'chikitsya-a1e2d',
    authDomain: 'chikitsya-a1e2d.firebaseapp.com',
    storageBucket: 'chikitsya-a1e2d.firebasestorage.app',
    measurementId: 'G-8HB3FFG2SJ',
  );
}
